export const CHAIN_ID = Number(
  process.env.REACT_APP_CHAIN_ID || 11155111
);

export const ADDRESSES = {
  MOCK_USDC: process.env.REACT_APP_MOCK_USDC!,
  PRICE_ORACLE: process.env.REACT_APP_PRICE_ORACLE!,
  GOVERNANCE: process.env.REACT_APP_GOVERNANCE!,
  INTEREST_RATE_MODEL: process.env.REACT_APP_INTEREST_RATE_MODEL!,
  COLLATERAL_VAULT: process.env.REACT_APP_COLLATERAL_VAULT!,
  LENDING_POOL: process.env.REACT_APP_LENDING_POOL!,
  LOAN_MANAGER: process.env.REACT_APP_LOAN_MANAGER!,
  LOAN_NFT: process.env.REACT_APP_LOAN_NFT!,
  POSITION_REGISTRY: process.env.REACT_APP_POSITION_REGISTRY!,

  SWAP_NFT: process.env.REACT_APP_SWAP_NFT!,
  SWAP_FACTORY: process.env.REACT_APP_SWAP_FACTORY!,
  SWAP_ENGINE: process.env.REACT_APP_SWAP_ENGINE!,

  SETTLEMENT_ENGINE:
    process.env.REACT_APP_SETTLEMENT_ENGINE!,

  NETTING_ENGINE:
    process.env.REACT_APP_NETTING_ENGINE!,

  ESCROW_MANAGER:
    process.env.REACT_APP_ESCROW_MANAGER!,

  DVP_ENGINE:
    process.env.REACT_APP_DVP_ENGINE!,

  LIQUIDATION_ENGINE:
    process.env.REACT_APP_LIQUIDATION_ENGINE!,
} as const;